### PR TITLE
Measurement

### PR DESCRIPTION
**Pull request by DocKDE**
I took the liberty of adding support for calculating angles and dihedral for atoms. I recently implemented this in my own crate and realized that it would make more sense to move this to the library.
Feel free to criticize :)

### CODE REVIEW

**Comment by douweschulte** [comment]
Very nice addition. I will gladly merge it into the library. But it would be really nice if you could add at least one unit test for the two functions added. That will enable future verification of changes to the functions.

**Comment by DocKDE** [comment]
Yes, of course I'll do it. I only remembered after I had created the PR and then wanted to wait for your feedback.

**Comment by DocKDE** [comment]
Ok, added a unit test for each function and renamed dihedral function to be more consistent.

**Comment by douweschulte** [comment]
Nice work

**Pull request merged**
