### PR TITLE
Downgrade remark type number invalid error

### LINKED ISSUE #123: Read option to only parse `ATOM` records
Although the library was designed to work with crystallographic files, many modeling software would also generate files of this format. These files usually only focus on atomic coordinates, and may come with some annotation data that often don't comply with the format specification. For example, Rosetta would generate `REMARK 220` fields in the header, which `pdbtbx` would complain with:

```
StrictWarning: Remark type number invalid
The remark-type-number is not valid, see wwPDB v3.30 for all valid numbers.
```

Currently there is support for parsing files with different `StrictnessLevel`s, and I was wondering if it would be possible to add an atoms-only parsing mode where all other information are skipped. This would be similar to running a `grep ^ATOM` prior to parsing with `pdbtbx`.

Thanks for the amazing library and I'm open to provide test cases or further details.

### PR DESCRIPTION
**Pull request by y1zhou**
Fixes #123 and adds a test PDB file containing such `REMARK` records.

### CODE REVIEW

**Comment by y1zhou** [comment]
@douweschulte It seems the `ReadOptions` hasn't made its way into the core parser yet? The `open_with_options` function only passes `ReadOptions.level` into the `open_pdb` / `open_mmcif` function and ignores all other fields.

https://github.com/douweschulte/pdbtbx/blob/7af6cc8448756e009e08651ca701dc8cb79c6c17/src/read/general.rs#L34-L50

To implement the `only_atomic_data` read option we'd need corresponding `open_pdb_with_options` and `open_mmcif_with_options` as well, right? I assume you don't want to modify the original signatures directly for backward compatibility.

**Comment by douweschulte** [comment]
Yes something like that has to be added. On not changing the API, you can change the 'core' methods (meaning the one that actually does the parsing), but make sure to keep this one private and keep the current open functions as calls to the core functions with the default `ReadOptions` for example.

**Comment by OWissett** [comment]
I have created another issue for finishing my implementation of the  `ReadOptions`. #125 

Sorry for leaving it half done, I got stuck with some other PhD work.

**Comment by y1zhou** [comment]
Cool I'll try to add in the functions that parse `ReadOptions`.

> Sorry for leaving it half done, I got stuck with some other PhD work.

No worries we are all aware how stressful that can be :)

**Review by douweschulte — APPROVED** [review]
Perfect!! I am fine with merging right away and doing the `only_load_atomic` together with #125 in another PR or doing that work right here whatever works best for you.

**Review by OWissett — APPROVED** [review]

**Comment by y1zhou** [comment]
> Perfect!! I am fine with merging right away and doing the `only_load_atomic` together with #125 in another PR or doing that work right here whatever works best for you.

Yes taking that in another PR seems more reasonable. Will send as more work is done!

**Pull request merged**
